# BSP options
SIMULATION_OPTIMIZED_SUPPORT="false"
BSP_TYPE=hal
BSP_FLAGS=" \
--set hal.enable_c_plus_plus 0 \
--set hal.enable_clean_exit 0 \
--set hal.enable_exit 0 \
--set hal.enable_gprof 0 \
--set hal.enable_lightweight_device_driver_api 1 \
--set hal.enable_mul_div_emulation 0 \
--set hal.enable_reduced_device_drivers 1 \
--set hal.enable_runtime_stack_checking 0 \
--set hal.enable_sim_optimize 0 \
--set hal.enable_small_c_library 1 \
--set hal.enable_sopc_sysid_check 1 \
--set hal.enable_sim_optimize $SIMULATION_OPTIMIZED_SUPPORT \
--set hal.make.bsp_cflags_optimization $OPTIMIZATION_LEVEL \
--set hal.linker.allow_code_at_reset 1 \
--set hal.linker.enable_alt_load 1 \
--set hal.linker.enable_alt_load_copy_exceptions 1 \
--set hal.linker.enable_alt_load_copy_rodata 0 \
--set hal.linker.enable_alt_load_copy_rwdata 1 \
--set hal.linker.enable_exception_stack 0 \
--set hal.linker.enable_interrupt_stack 0 \
--set hal.linker.exception_stack_memory_region_name $SOPC_DATA_MEMORY_NAME \
--set hal.linker.interrupt_stack_memory_region_name $SOPC_DATA_MEMORY_NAME \
--set hal.make.ignore_system_derived.big_endian 0 \
--set hal.make.ignore_system_derived.debug_core_present 0 \
--set hal.make.ignore_system_derived.fpu_present 0 \
--set hal.make.ignore_system_derived.hardware_divide_present 0 \
--set hal.make.ignore_system_derived.hardware_fp_cust_inst_divider_present 0 \
--set hal.make.ignore_system_derived.hardware_fp_cust_inst_no_divider_present 0 \
--set hal.make.ignore_system_derived.hardware_multiplier_present 0 \
--set hal.make.ignore_system_derived.hardware_mulx_present 0 \
--set hal.make.ignore_system_derived.sopc_simulation_enabled 0 \
--set hal.make.ignore_system_derived.sopc_system_base_address 0 \
--set hal.make.ignore_system_derived.sopc_system_id 0 \
--set hal.make.ignore_system_derived.sopc_system_timestamp 0 \
--set hal.max_file_descriptors 4 \
--set hal.stderr none \
--set hal.stdin none \
--set hal.stdout none \
--set hal.sys_clk_timer none \
--set altera_vic_driver.linker_section .rwdata \
--script set_app_regions.tcl \
--cmd set_driver none iptronix_generic_quad_spi_controller2_0 \
--cmd set_driver none flash_spi \
--cmd add_section_mapping .rwdata onchip_memory2_0 \
--cmd add_section_mapping .bss onchip_memory2_0 \
--cmd add_section_mapping .heap onchip_memory2_0 \
--cmd add_section_mapping .entry iptronix_generic_quad_spi_controller2_0_avl_mem \
--cmd add_section_mapping .text iptronix_generic_quad_spi_controller2_0_avl_mem \
--cmd add_section_mapping .rodata iptronix_generic_quad_spi_controller2_0_avl_mem \
--cmd add_section_mapping .data iptronix_generic_quad_spi_controller2_0_avl_mem \
--cmd add_section_mapping .stack onchip_memory2_0  \
"