=GFX IP RPC


== Configuration options

.Options
[%autowidth]
|=====================================================================================================
^|Option ^|Default ^|Description

^|GFX_FB_WIDTH   |640 |
^|GFX_FB_HEIGHT  |480 |
^|GFX_CAM_BASE   |SDRAM_ARBITER_BASE + SDRAM_ARBITER_CAM_OFFSET_A * sizeof(short) |
^|GFX_FB_BASE    |SDRAM_ARBITER_BASE + SDRAM_ARBITER_FB_OFFSET * sizeof(short) |
^|GFX_FONTS      |1         |
^|GFX_FONT_FILE  |Org_01.h  |
^|GFX_FONT_NAME  |Org_01    |
^|GFX_LOGO       |1         |
^|GFX_LOGO_FILE  |logo.h    |
^|GFX_LOGO_NAME  |arduinoLogo |
|=====================================================================================================


== GFX RPC

.Commands
[%autowidth]
|=====================================================================================================
^|Cmd ^|Description ^|Parameters ^|Return

^| 2 ^|Setup            ^|none                  |RetCod
^| 4 ^|End              ^|none                  |RetCod
^| 5 ^|writePixel       ^|x, y, color           |RetCod
^| 6 ^|writeLine        ^|x0, y0, x1, y1, color |RetCod
^| 7 ^|drawRect         ^|x, y, w, h, color     |RetCod
^| 8 ^|fillRect         ^|x, y, w, h, color     |RetCod
^| 9 ^|drawCircle       ^|x, y, r, color        |RetCod
^|10 ^|fillCircle       ^|x, y, r, color        |RetCod
^|11 ^|drawChar         ^|x, y, color, size, c  |Width of drawed char
^|12 ^|drawTxt          ^|x, y, color, txt      |Width of drawed text
^|13 ^|setFont          ^|font index            |RetCod
^|14 ^|setCursor        ^|x, y                  |RetCod
^|15 ^|setTextSize      ^|Size                  |RetCod
^|16 ^|setTextColor     ^|Color (RGB24)         |RetCod
^|17 ^|setTextAlpha     ^|Alpha                 |RetCod
^|18 ^|drawCharAtCursor ^|Char                  |RetCod
|=====================================================================================================

