= JTAG_BRIDGE IP core

Implements a bridge between a virtual JTAG interface and an avalon bus.

== Ports

.Ports
[%autowidth]
|=====================================================================================================
     ^|Signal Group  ^|Signal Name       ^|Direction ^|Width ^|Description

.2+^.^|Clock/Reset    |iCLK              ^|Input     ^|   1   |Avalon clock                  
                      |iRESET            ^|Input     ^|   1   |Avalon Reset                  
.8+^.^|Avalon Master  |oADDRESS          ^|Output    ^|  32   |Address                       
                      |oWRITE            ^|Output    ^|   1   |Write request                 
                      |oREAD             ^|Output    ^|   1   |Read request                  
                      |oWRITE_DATA       ^|Output    ^|  32   |Fata to be written            
                      |iREAD_DATA        ^|Input     ^|  32   |Fata being read               
                      |oBURST_COUNT      ^|Output    ^|   5   |Number of words to read/write 
                      |iWAIT_REQUEST     ^|Input     ^|   1   |Wait request from slave       
                      |iREAD_DATA_VALID  ^|Input     ^|   1   |data valid flag from slave    
.2+^.^|Event Slave    |iEVENT_WRITE_DATA ^|Output    ^|  32   |event data                    
                      |iEVENT_WRITE      ^|Output    ^|   1   |Write request                 
     ^|Event irq      |oEVENT_EMPTY      ^|Output    ^|   1   |event queue empty irq         
|=====================================================================================================

== Parameters

The IP has no parameters

== Description

*JTAG_BRIDGE* core allows translating Virtual JTAG commands into avalon bus transactions. Virtual JTAG is an Intel IP core that implements a virtual JTAG scan chain that allows having multiple IP blocks each with a virtual instruction register (VIR) and a virtual data register (VDR).
Bridge operates in a similar way to I2C in the sense that it has an instruction for setting address and writing data and an instruction to read data using the address previously set by the write instruction (eventually with no payload). As wit I2C it is possible to read and write multiple words in a single transaction, in which case address will automatically increment.
VIR size is 3 bits and implements the following commands:

.Commands
[%autowidth]
|=====================================================================================================
^|Command           ^|VIR value ^|Description

^|Write/Set address ^|   0       |sets address and, if data is present, writes data to slave        
^|Read              ^|   1       |Reads data from address previously set through Write instruction  
^|Read Event FIFO   ^|   2       |Reads data event FIFO                                             
|=====================================================================================================

To perform a write transaction it's necessary to set VIR to 0 and then write in VDR address and data. 
In order to optimize JTAG transactions address can be set up with 8, 16, 24 or 32 bits. since data bus is 32 bit, the two LSBs of the address are used to determine address size. This means that if the two LSBs of the address are 00 the IP expects only 8 address bits after which subsequent bits are treated as data words to write. If a read operation is required, after address bits are sent transaction can be concluded.

[NOTE]
======
that read operation reads data before data is shifted out so this means that first word is read as soon as VIR is set to 1 and a new word is read as soon as the previous one starts being shifted out. This means that an extra read will be performed when shifting out the last bit of the last word being read out from jtag and care should be taken if that register has bits that change value if read as those values would be lost.in order to prevent this it's necessary to set TDI high during the last cycle of the out shift or, in case only a word is being shifted out, during the transition from Capture-DR to Shift-DR
======

==Events
In order to send events to the external processor the IP has a slave port where a single event can be written. It is expected that external processor will signal the availability of the event with an external pin and as soon as the event starts to being shifted out an interrupt is issued to the soft core to allow loading a new event if necessary and to update the state of the event flag to the external processor.