# TCL File Generated by Component Editor 17.1
# Wed May 02 16:39:39 CEST 2018
# DO NOT MODIFY


# 
# JTAG_BRIDGE "JTAG Bridge" v1.0
#  2018.05.02.16:39:39
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module JTAG_BRIDGE
# 
set_module_property DESCRIPTION ""
set_module_property NAME JTAG_BRIDGE
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ipTronix
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "JTAG Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL JTAG_BRIDGE
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file JTAG_BRIDGE.v VERILOG PATH JTAG_BRIDGE.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master oADDRESS address Output 32
add_interface_port avalon_master oWRITE write Output 1
add_interface_port avalon_master oREAD read Output 1
add_interface_port avalon_master oWRITE_DATA writedata Output 32
add_interface_port avalon_master iREAD_DATA readdata Input 32
add_interface_port avalon_master iWAIT_REQUEST waitrequest Input 1
add_interface_port avalon_master iREAD_DATA_VALID readdatavalid Input 1

#
# connection point event
#
add_interface event avalon end
set_interface_property event addressUnits WORDS
set_interface_property event associatedClock clock
set_interface_property event associatedReset reset
set_interface_property event bitsPerSymbol 8
set_interface_property event burstOnBurstBoundariesOnly false
set_interface_property event burstcountUnits WORDS
set_interface_property event explicitAddressSpan 0
set_interface_property event holdTime 0
set_interface_property event linewrapBursts false
set_interface_property event maximumPendingReadTransactions 0
set_interface_property event maximumPendingWriteTransactions 0
set_interface_property event readLatency 1
set_interface_property event readWaitTime 0
set_interface_property event setupTime 0
set_interface_property event timingUnits Cycles
set_interface_property event writeWaitTime 0
set_interface_property event ENABLED true
set_interface_property event EXPORT_OF ""
set_interface_property event PORT_NAME_MAP ""
set_interface_property event CMSIS_SVD_VARIABLES ""
set_interface_property event SVD_ADDRESS_GROUP ""

add_interface_port event iEVENT_WRITE_DATA writedata Input 32
add_interface_port event iEVENT_WRITE write Input 1
set_interface_assignment event embeddedsw.configuration.isFlash 0
set_interface_assignment event embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment event embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment event embeddedsw.configuration.isPrintableDevice 0

#
# connection point irq
#
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint "event"
set_interface_property irq associatedClock clock
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq oEVENT_EMPTY irq Output 1
# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset iRESET reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock iCLK clk Input 1

