# (C) 2001-2018 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 16.1
# Tue Jun 21 01:26:17 MYT 2016
# DO NOT MODIFY


# 
# altera_asmi2_qspi_interface "Altera ASMI2 QSPI Interface" v1.0
#  2016.06.21.01:26:17
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.1
package require -exact altera_terp 1.0


# 
# module altera_asmi2_qspi_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME iptronix_asmi2_qspi_interface
set_module_property VERSION 18.0
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Configuration and Programming"
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "Altera ASMI2 QSPI Interface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

set_module_property     ELABORATION_CALLBACK    elaboration

# ----------------------------------------------------------------------
# 
# parameters
# 

# Data width
add_parameter           DATA_WIDTH  STRING              "STANDARD"
set_parameter_property  DATA_WIDTH  DISPLAY_NAME        "Choose I/O mode"
set_parameter_property  DATA_WIDTH  ALLOWED_RANGES      {"NORMAL" "STANDARD" "DUAL" "QUAD"}
set_parameter_property  DATA_WIDTH  DESCRIPTION         "Select extended data width when Fast Read operation is enabled"
set_parameter_property  DATA_WIDTH  AFFECTS_GENERATION  true

# Check to disable auto-instantiation of asmiblock, and route the interface to top level
add_parameter           DISABLE_ASMIBLOCK    BOOLEAN             0
set_parameter_property  DISABLE_ASMIBLOCK    DISPLAY_NAME        "Disable dedicated Active Serial interface"
set_parameter_property  DISABLE_ASMIBLOCK    DESCRIPTION         "Check to route ASMIBLOCK signals to top level of design"
set_parameter_property  DISABLE_ASMIBLOCK    AFFECTS_GENERATION  true

# Check to translate the interface to SPI pins
add_parameter           USE_GPIO    BOOLEAN             0
set_parameter_property  USE_GPIO    DISPLAY_NAME        "Enable SPI pins interface"
set_parameter_property  USE_GPIO    DESCRIPTION         "Check to translate ASMIBLOCK signals to SPI pins interface"
set_parameter_property  USE_GPIO    AFFECTS_GENERATION  true

# Check the number of ncs connected to flash
add_parameter           NCS_NUM     INTEGER             1
set_parameter_property  NCS_NUM     DISPLAY_NAME        "Number of Chip Select"
set_parameter_property  NCS_NUM     ALLOWED_RANGES      {1:16}
set_parameter_property  NCS_NUM     DESCRIPTION         "Select the number of chip select connected to flash"
set_parameter_property  NCS_NUM     AFFECTS_GENERATION  true

add_parameter           ENABLE_SIM  BOOLEAN             0
set_parameter_property  ENABLE_SIM  DISPLAY_NAME        "Enable simulation"
set_parameter_property  ENABLE_SIM  DESCRIPTION         "Check to enable simulation for Active Serial pins"
set_parameter_property  ENABLE_SIM  AFFECTS_GENERATION  true

# Device family
add_parameter           DEV_FAMILY  STRING              "Arria 10"
set_parameter_property  DEV_FAMILY  SYSTEM_INFO         {DEVICE_FAMILY}
set_parameter_property  DEV_FAMILY  AFFECTS_GENERATION  true
set_parameter_property  DEV_FAMILY  VISIBLE             false
set_parameter_property  DEV_FAMILY  HDL_PARAMETER       true

# NCS length
add_parameter           NCS_LENGTH  INTEGER             3
set_parameter_property  NCS_LENGTH  AFFECTS_GENERATION  true
set_parameter_property  NCS_LENGTH  VISIBLE             false
set_parameter_property  NCS_LENGTH  HDL_PARAMETER       true
set_parameter_property  NCS_LENGTH  DERIVED             true

# Data length
add_parameter           DATA_LENGTH  INTEGER            4
set_parameter_property  DATA_LENGTH  AFFECTS_GENERATION true
set_parameter_property  DATA_LENGTH  VISIBLE            false
set_parameter_property  DATA_LENGTH  HDL_PARAMETER      true
set_parameter_property  DATA_LENGTH  DERIVED            true

# Mode length
add_parameter           MODE_LENGTH  INTEGER            1
set_parameter_property  MODE_LENGTH  AFFECTS_GENERATION true
set_parameter_property  MODE_LENGTH  VISIBLE            false
set_parameter_property  MODE_LENGTH  HDL_PARAMETER      true
set_parameter_property  MODE_LENGTH  DERIVED            true

# Simulation model
add_parameter           ENABLE_SIM_MODEL  STRING            "false"
set_parameter_property  ENABLE_SIM_MODEL  AFFECTS_GENERATION true
set_parameter_property  ENABLE_SIM_MODEL  VISIBLE            false
set_parameter_property  ENABLE_SIM_MODEL  HDL_PARAMETER      true
set_parameter_property  ENABLE_SIM_MODEL  DERIVED            true

# ----------------------------------------------------------------------
# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH generate_synth
set_fileset_property QUARTUS_SYNTH TOP_LEVEL iptronix_asmi2_qspi_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true

add_fileset SIM_VERILOG SIM_VERILOG generate_sim
set_fileset_property SIM_VERILOG TOP_LEVEL iptronix_asmi2_qspi_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true

add_fileset SIM_VHDL SIM_VHDL generate_sim
set_fileset_property SIM_VHDL TOP_LEVEL iptronix_asmi2_qspi_interface
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true

proc generate_synth {entity_name} {
    
    generate_fileset synth_files
}

proc generate_sim {entity_name} {
    
    generate_fileset sim_files
}

proc generate_fileset {flag} {
    
    if { [get_parameter_value USE_GPIO] } {
        set use_gpio   "true"
        set disable_asmiblock "false"
        add_fileset_file altera_asmi2_qspi_interface_gpio.sv SYSTEM_VERILOG PATH altera_asmi2_qspi_interface_gpio.sv
        
    } elseif { [get_parameter_value DISABLE_ASMIBLOCK] } {
        set use_gpio   "false"
        set disable_asmiblock "true"

    } else {
        set use_gpio   "false"
        set disable_asmiblock "false"
        
        if { $flag eq "synth_files" } {
            add_fileset_file altera_asmi2_qspi_interface_asmiblock.sv SYSTEM_VERILOG PATH altera_asmi2_qspi_interface_asmiblock.sv
        } else {
			add_fileset_file altera_asmi2_qspi_interface_asmiblock.sv SYSTEM_VERILOG PATH altera_asmi2_qspi_interface_asmiblock.sv
            # for debug purpose now
            #add_fileset_file altera_asmi2_qspi_interface_asmiblock.sv VERILOG PATH altera_asmi2_qspi_interface_asmiblock_sim.v
        }
    }
    
    set this_dir      [ get_module_property MODULE_DIRECTORY ]
    set template_file [ file join $this_dir "iptronix_asmi2_qspi_interface.sv.terp" ]
    set template      [ read [ open $template_file r ] ]
    
    set params(use_gpio)            $use_gpio
    set params(disable_asmiblock)   $disable_asmiblock
    set params(data_width)          [get_parameter_value DATA_WIDTH]
    set result          [ altera_terp $template params ]
    
    set output_file     [ create_temp_file iptronix_asmi2_qspi_interface.sv ]
    set output_handle   [ open $output_file w ]
    puts $output_handle $result
    close $output_handle
    
    add_fileset_file iptronix_asmi2_qspi_interface.sv SYSTEM_VERILOG PATH ${output_file}
}


# ----------------------------------------------------------------------
# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point in_cmd_pck
# 
add_interface in_cmd_pck avalon_streaming end
set_interface_property in_cmd_pck associatedClock clk
set_interface_property in_cmd_pck associatedReset reset
set_interface_property in_cmd_pck dataBitsPerSymbol 8
set_interface_property in_cmd_pck errorDescriptor ""
set_interface_property in_cmd_pck firstSymbolInHighOrderBits true
set_interface_property in_cmd_pck maxChannel 0
set_interface_property in_cmd_pck readyLatency 0
set_interface_property in_cmd_pck ENABLED true
set_interface_property in_cmd_pck EXPORT_OF ""
set_interface_property in_cmd_pck PORT_NAME_MAP ""
set_interface_property in_cmd_pck CMSIS_SVD_VARIABLES ""
set_interface_property in_cmd_pck SVD_ADDRESS_GROUP ""

add_interface_port in_cmd_pck in_cmd_channel channel Input 2
add_interface_port in_cmd_pck in_cmd_eop endofpacket Input 1
add_interface_port in_cmd_pck in_cmd_ready ready Output 1
add_interface_port in_cmd_pck in_cmd_sop startofpacket Input 1
add_interface_port in_cmd_pck in_cmd_data data Input 8
add_interface_port in_cmd_pck in_cmd_valid valid Input 1


# 
# connection point out_rsp_pck
# 
add_interface out_rsp_pck avalon_streaming start
set_interface_property out_rsp_pck associatedClock clk
set_interface_property out_rsp_pck associatedReset reset
set_interface_property out_rsp_pck dataBitsPerSymbol 8
set_interface_property out_rsp_pck errorDescriptor ""
set_interface_property out_rsp_pck firstSymbolInHighOrderBits true
set_interface_property out_rsp_pck maxChannel 0
set_interface_property out_rsp_pck readyLatency 0
set_interface_property out_rsp_pck ENABLED true
set_interface_property out_rsp_pck EXPORT_OF ""
set_interface_property out_rsp_pck PORT_NAME_MAP ""
set_interface_property out_rsp_pck CMSIS_SVD_VARIABLES ""
set_interface_property out_rsp_pck SVD_ADDRESS_GROUP ""

add_interface_port out_rsp_pck out_rsp_data data Output 8
add_interface_port out_rsp_pck out_rsp_valid valid Output 1
add_interface_port out_rsp_pck out_rsp_ready ready Input 1

#add_interface_port out_rsp_pck out_rsp_channel channel Output 2
#add_interface_port out_rsp_pck out_rsp_eop endofpacket Output 1
#add_interface_port out_rsp_pck out_rsp_sop startofpacket Output 1


# 
# connection point dummy_cycles
# 
add_interface dummy_cycles conduit end
set_interface_property dummy_cycles associatedClock clk
set_interface_property dummy_cycles associatedReset ""
set_interface_property dummy_cycles ENABLED true
set_interface_property dummy_cycles EXPORT_OF ""
set_interface_property dummy_cycles PORT_NAME_MAP ""
set_interface_property dummy_cycles CMSIS_SVD_VARIABLES ""
set_interface_property dummy_cycles SVD_ADDRESS_GROUP ""

add_interface_port dummy_cycles dummy_cycles dummy_cycles Input 5

# 
# connection point chip_select
# 
add_interface chip_select conduit end
set_interface_property chip_select associatedClock clk
set_interface_property chip_select associatedReset ""
set_interface_property chip_select ENABLED true
set_interface_property chip_select EXPORT_OF ""
set_interface_property chip_select PORT_NAME_MAP ""
set_interface_property chip_select CMSIS_SVD_VARIABLES ""
set_interface_property chip_select SVD_ADDRESS_GROUP ""

add_interface_port chip_select chip_select chip_select Input 4

# 
# connection point qspi_interface_en
# 
add_interface qspi_interface_en conduit end
set_interface_property qspi_interface_en associatedClock clk
set_interface_property qspi_interface_en associatedReset ""
set_interface_property qspi_interface_en ENABLED true
set_interface_property qspi_interface_en EXPORT_OF ""
set_interface_property qspi_interface_en PORT_NAME_MAP ""
set_interface_property qspi_interface_en CMSIS_SVD_VARIABLES ""
set_interface_property qspi_interface_en SVD_ADDRESS_GROUP ""

add_interface_port qspi_interface_en qspi_interface_en qspi_interface_en Input 1


# 
# connection point require_rdata
# 
add_interface require_rdata conduit end
set_interface_property require_rdata associatedClock clk
set_interface_property require_rdata associatedReset ""
set_interface_property require_rdata ENABLED true
set_interface_property require_rdata EXPORT_OF ""
set_interface_property require_rdata PORT_NAME_MAP ""
set_interface_property require_rdata CMSIS_SVD_VARIABLES ""
set_interface_property require_rdata SVD_ADDRESS_GROUP ""

add_interface_port require_rdata require_rdata require_rdata Input 1


# ----------------------------------------------------------------------
# 
# elaboration callback
# 
proc elaboration {} {
    set disable_asmiblock   [get_parameter_value DISABLE_ASMIBLOCK]
    set use_gpio            [get_parameter_value USE_GPIO]
    set user_ncs_num        [get_parameter_value NCS_NUM]
    set dev_family          [get_parameter_value DEV_FAMILY]
    set data_width_mode     [get_parameter_value DATA_WIDTH]
    set enable_sim          [get_parameter_value ENABLE_SIM]
    
    if { $use_gpio } {
        set_parameter_property NCS_NUM VISIBLE true 
    } else {
        set_parameter_property NCS_NUM VISIBLE false 
    }

    set device_28nm {"Cyclone V" "Arria V GZ" "Arria V" "Stratix V"}
    
    if {$use_gpio} {
        set ncs_count   $user_ncs_num
        set data_count  4
        
    } elseif {[check_device_family_equivalence $dev_family "Arria 10"] || [check_device_family_equivalence $dev_family "Cyclone 10 GX"]} {
        set ncs_count   3
        set data_count  4

    } else {
        set ncs_count   1

        if { [check_device_family_equivalence $dev_family $device_28nm] || [check_device_family_equivalence $dev_family "Cyclone 10 LP"]} {
            set data_count  4
        } else {
            set data_count  2
        } 
    } 

    if {$data_width_mode == "STANDARD" || $data_width_mode == "NORMAL"} {
        set mode_count 1
    } elseif {$data_width_mode == "DUAL"} {
        set mode_count 2
    } else {
        set mode_count 4
    }

    if {$enable_sim} {
        set enable_sim_model "true"
    } else {
        set enable_sim_model "false"
    }
    set_parameter_value NCS_LENGTH  $ncs_count
    set_parameter_value DATA_LENGTH $data_count
    set_parameter_value MODE_LENGTH $mode_count
    set_parameter_value ENABLE_SIM_MODEL $enable_sim_model
    
    if { $use_gpio } {
        add_interface qspi_pins conduit end
        set_interface_property qspi_pins associatedClock clk
        set_interface_property qspi_pins associatedReset ""
        set_interface_property qspi_pins ENABLED true
        set_interface_property qspi_pins EXPORT_OF ""
        set_interface_property qspi_pins PORT_NAME_MAP ""
        set_interface_property qspi_pins CMSIS_SVD_VARIABLES ""
        set_interface_property qspi_pins SVD_ADDRESS_GROUP ""
        
        add_interface_port qspi_pins qspi_pins_dclk dclk    Output  1
        add_interface_port qspi_pins qspi_pins_ncs  ncs     Output  $ncs_count
        add_interface_port qspi_pins qspi_pins_data data    Bidir   4
        
    } elseif { $disable_asmiblock } {
        add_interface atom_ports conduit end
        set_interface_property atom_ports associatedClock clk
        set_interface_property atom_ports associatedReset ""
        set_interface_property atom_ports ENABLED true
        set_interface_property atom_ports EXPORT_OF ""
        set_interface_property atom_ports PORT_NAME_MAP ""
        set_interface_property atom_ports CMSIS_SVD_VARIABLES ""
        set_interface_property atom_ports SVD_ADDRESS_GROUP ""
        
        add_interface_port atom_ports atom_ports_dclk       dclk    Output  1
        add_interface_port atom_ports atom_ports_ncs        ncs     Output  $ncs_count
        add_interface_port atom_ports atom_ports_oe         oe      Output  1
        add_interface_port atom_ports atom_ports_dataout    dataout Output  4
        add_interface_port atom_ports atom_ports_dataoe     dataoe  Output  4
        add_interface_port atom_ports atom_ports_datain     datain  Input   4
    }
}
